kind: Cluster
apiVersion: kind.x-chart.io/v1alpha4
networking:
  apiServerAddress: 127.0.0.1
  apiServerPort: 34323
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
- role: worker
kubeadmConfigPatches:
- |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  evictionHard:
    nodefs.available: "0%"

