# this config file contains all config fields with comments
# NOTE: this is not a particularly useful config file
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: 127.0.0.1
  apiServerPort: 34323
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
#  extraPortMappings:
# Grafana UI port forward 3001 on the host to 30071 on cluster node
#  - containerPort: 30071
#    hostPort: 3001
# Prometheus UI port forward 3002 on the host to 30909 on cluster node
#  - containerPort: 30909
#    hostPort: 3002
# the three workers
- role: worker
- role: worker
- role: worker
kubeadmConfigPatches:
- |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  evictionHard:
    nodefs.available: "0%"
# patch it further using a JSON 6902 patch
kubeadmConfigPatchesJSON6902:
- group: kubeadm.k8s.io
  version: v1beta2
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: my-hostname  
