global:
    scrape_interval: 10s

scrape_configs:
    - job_name: blackbox
      metrics_path: /probe
      params:
        module: [icmp_ipv4]
      static_configs:
        - targets:
          - 1.1.1.1      # CloudFlare DNS
          - 184.51.10.83 # www.microsoft.com
          - 193.17.47.1  # CZ-NIC DNS
          - google.com
          - vyznanie.sk
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: ping-blackbox:9115
