apiVersion: v2
name: dnation-ping
version: 0.1.0
appVersion: 0.1.3
description: dNation Ping is a transparent tool for pinging selected IP addresses or domain names in set intervals with results displayed on graph
keywords:
  - kubernetes
  - ping
  - grafana
  - prometheus
  - blackbox-exporter
home: https://git.ifne.eu/dnation/ping
dependencies:
- name: prometheus
  version: "11.16.*"
  repository: https://prometheus-community.github.io/helm-charts
  condition: prometheus.enabled
- name: grafana
  version: "5.7.*"
  repository: https://grafana.github.io/helm-charts
  condition: grafana.enabled
maintainers:
- name: dnation
  email: admin@dnation.tech
icon: https://storage.googleapis.com/ifne.eu/public/icons/dnation_ping.svg


