apiVersion: v2
name: dnation-ping
version: 0.1.0
appVersion: 0.1.3
description: dNation Ping is a transparent tool for pinging selected IP addresses or domain names in set intervals with results displayed on graph
keywords:
  - kubernetes
  - ping
  - grafana
  - prometheus
  - blackbox-exporter
home: https://git.ifne.eu/dnation/ping
