apiVersion: v1
data:
  config.yml: |+
    modules:
      icmp_ipv4:
        prober: icmp
        icmp:
          preferred_ip_protocol: "ip4"

      #http_2xx:
       # prober: http
        #http:
         # preferred_ip_protocol: "ip4"


kind: ConfigMap
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:config.yml: {}
    manager: kubectl-create
    operation: Update
    time: "2020-09-08T12:08:18Z"
  name: blackbox-config
  namespace: default
  resourceVersion: "77826"
---
apiVersion: v1
data:
  prometheus.yaml: |
    global:
        scrape_interval: 10s

    scrape_configs:
        - job_name: blackbox
          metrics_path: /probe
          params:
            module: [icmp_ipv4]
          file_sd_configs:
          - files:
            - '/etc/targets/targets.json'
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: ping-blackbox:9115
kind: ConfigMap
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data: {}
    manager: kubectl-create
    operation: Update
    time: "2020-09-08T12:06:08Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:prometheus.yaml: {}
    manager: kubectl-edit
    operation: Update
    time: "2020-09-09T11:21:42Z"
  name: prometheus-config
  namespace: default
  resourceVersion: "139261"
