apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-targets
data:
  targets.json: |-
    [
      {
        "labels": {
          "job": "blackbox"
        },
        "targets": [
          "1.1.1.1",
          "184.51.10.83",
          "193.17.47.1",
          "google.com",
          "vyznanie.sk",
          "zob.sk",
          "facebook.com",
          "sme.sk"
        ]
      }
    ]


