grafana:
  adminUser: admin
  adminPassword: pass
  service:
    type: NodePort
    nodePort: 30071
    port: 3000
    targetPort: http
  replicas: 1

prometheus:
  service:
    type: NodePort
    nodePort: 30909
    port: 9090
    targetPort: 9090
  global:
    scrapeInterval: 10s
  targets:
  - 1.1.1.1
  - 184.51.10.83
  - 193.17.47.1
  - google.com
  - vyznanie.sk
  - zob.sk