dnation:
  ingress:
    enabled: false
  certificate:
    enabled: false

grafana:
    adminUser: "admin"
    adminPassword: "pass"
    replicas: 1
    deploymentStrategy:
      type: RollingUpdate
    env: {
      env:
      - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
        valueFrom: /etc/grafana/dashboards-json/ping-dashboard.json
    }
    dashboards: {
      default:
        custom-dashboard:
          file: dashboards/ping-dashboard.json
    }
    datasources: {
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus:9090
          isDefault: true
    }
    service:
      type: ClusterIP
      port: 80
      targetPort: 3000
      annotations: { }
      labels: { }
      portName: service
    extraConfigmapMounts:
    - name: dnation-ping-icon
      mountPath: /usr/share/grafana/public/img/grafana_icon.svg
      subPath: grafana_icon.svg
      configMap: dnation-ping-icon
      readOnly: true


prometheus:
  service:
    type: NodePort
    nodePort: 30909
    port: 9090
    targetPort: 9090
  global:
    scrapeInterval: 10s
  persistence:
    enabled: false
  targets:
  - 1.1.1.1
  - 184.51.10.83
  - 193.17.47.1
  - google.com
  - vyznanie.sk
  - zob.sk

