dnation:
  ingress:
    enabled: false
  certificate:
    enabled: false

grafana:
    enabled: true
    adminUser: "admin"
    adminPassword: "pass"
    replicas: 1
    deploymentStrategy:
      type: RollingUpdate
    env: {
      env:
      - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
        valueFrom: /etc/grafana/dashboards-json/ping-dashboard.json
    }
    dashboards: {
      default:
        custom-dashboard:
          file: dashboards/ping-dashboard.json
    }
    datasources: {
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus:9090
          isDefault: true
    }
    service:
      type: ClusterIP
      port: 3000
      targetPort: 3000
      portName: service
    extraConfigmapMounts:
    - name: dnation-ping-icon
      mountPath: /usr/share/grafana/public/img/grafana_icon.svg
      subPath: grafana_icon.svg
      configMap: dnation-ping-icon
      readOnly: true


prometheus:
  enabled: true
  server:
    enabled: true
    name: server
    configPath: /etc/config/prometheus.yml
    global:
      scrapeInterval: 10s
    extraArgs: {
    - --storage.tsdb.path=/prometheus
    - --storage.tsdb.retention.time=365d
    - --query.lookback-delta=2m
    - --web.listen-address=0.0.0.0:9090
    }
    emptyDir:
      sizeLimit: "4Gi"
    replicaCount: 1
    service:
      servicePort: 9090
        type: ClusterIP
    prometheus.yml:
      scrape_configs:
        - job_name: prometheus
          metrics_path: /probe
          params:
            module: [ icmp_ipv4 ]
          static_configs:
            - targets:
                - 1.1.1.1
                - 184.51.10.83
                - 193.17.47.1
                - google.com
                - vyznanie.sk
                - zob.sk
          relabel_configs:
            - source_labels: [ __address__ ]
              target_label: __param_target
            - source_labels: [ __param_target ]
              target_label: instance
            - target_label: __address__
              replacement: localhost:9115
    sidecarContainers:
      - name: ping-blackbox
        image: prom/blackbox-exporter:master
        volumeMounts:
        - name: config-blackbox
        mountPath: "/etc/blackbox_exporter"
        readOnly: true
    extraVolumes: [
      - name: config-blackbox
        configMap:
          name: blackbox-config
    ]
