# ping dNation k8s cluster installation
# $ kubectl create namespace dnation-ping
# $ helm install dnation-ping ./k8s --namespace dnation-ping -f k8s/values-dnation.yaml
dnation:
  ingress:
    enabled: true
  certificate:
    enabled: true

grafana:
  adminUser: admin
  adminPassword: sl7+E4GzhV568
  service:
    type: NodePort
    nodePort: 30071
    port: 3000
    targetPort: http
  replicas: 1

prometheus:
  server:
    retention: 365d
    global:
      scrape_interval: 10s
  service:
    type: NodePort
    nodePort: 30909
    port: 9090
    targetPort: 9090
  global:
    scrapeInterval: 10s
  persistence:
    enabled: true
    storageClassName: hcloud-volumes
    accessModes:
    - ReadWriteOnce
    size: 10Gi
  targets:
  - 1.1.1.1
  - 184.51.10.83
  - 193.17.47.1
  - google.com
  - vyznanie.sk
  - zob.sk

