apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  replicas: {{ .Values.grafana.replicas }}
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana/grafana:latest
        name: grafana
        ports:
        - containerPort: {{ .Values.grafana.service.port }}
          name: {{ .Values.grafana.service.targetPort }}
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: {{ .Values.grafana.adminPassword }}
        - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
          value: /etc/grafana/dashboards-json/Ping.json
        volumeMounts:
        - name: dashboards-json
          mountPath: "/etc/grafana/dashboards-json"
          readOnly: true
        - name: dashboards
          mountPath: "/etc/grafana/provisioning/dashboards"
          readOnly: true
        - name: datasources
          mountPath: "/etc/grafana/provisioning/datasources"
          readOnly: true
        - name: ping-icon
          mountPath: "/usr/share/grafana/public/img/grafana_icon.svg"
          subPath: grafana_icon.svg
      volumes: 
      - name: dashboards-json
        configMap:
          name: grafana-dashboard-config
      - name: dashboards
        configMap:
          name: grafana-provisioning-dashboard
      - name: datasources
        configMap:
          name: grafana-datasources
      - name: ping-icon
        configMap:
          name: icon-config
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - port: {{ .Values.grafana.service.port }}
    protocol: TCP
    targetPort: {{ .Values.grafana.service.targetPort }}
    nodePort: {{ .Values.grafana.service.nodePort }}
  type: {{ .Values.grafana.service.type }}

