apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config
data:
  config.yml: |+
    modules:
      icmp_ipv4:
        prober: icmp
        icmp:
          preferred_ip_protocol: "ip4"

      #http_2xx:
       # prober: http
        #http:
         # preferred_ip_protocol: "ip4"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    global:
        scrape_interval: {{ .Values.prometheus.global.scrapeInterval }}

    scrape_configs:
        - job_name: blackbox
          metrics_path: /probe
          params:
            module: [icmp_ipv4]
          file_sd_configs:
          - files:
            - '/etc/targets/targets.json'
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: localhost:9115
