global:
    scrape_interval: 10s

scrape_configs:
    - job_name: blackbox
      metrics_path: /probe
      params:
        module: [icmp_ipv4]
      file_sd_configs:
      - files:
        - '/etc/targets.json'
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: localhost:9115
